name: justfart
description: "Just Fart — enregistre, collectionne et partage tes pets."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^6.2.0          # capture audio
  audioplayers: ^6.1.0    # lecture audio
  path_provider: ^2.1.4   # dossier de stockage local
  shared_preferences: ^2.3.2  # persistance des métadonnées
  share_plus: ^10.0.2     # partage natif (WhatsApp, Insta...)
  uuid: ^4.5.0            # identifiants uniques
  intl: ^0.19.0           # formatage des dates
  geolocator: ^14.0.2     # géolocalisation (natif + web via geolocator_web)
  flutter_map: ^8.3.1     # carte OpenStreetMap, sans clé API
  latlong2: ^0.10.1       # type LatLng utilisé par flutter_map

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
